module.exports = {
  '--global-font-size': '15px',
  '--global-line-height': '1.4em',
  '--global-space': '10px',
  '--font-stack': 'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif',
  '--mono-font-stack': 'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif',
  '--background-color': '#fff',
  '--page-width': '60em',
  '--font-color': '#151515',
  '--invert-font-color': '#fff',
  '--primary-color': '#1a95e0',
  '--secondary-color': '#727578',
  '--error-color': '#d20962',
  '--progress-bar-background': '#727578',
  '--progress-bar-fill': '#151515',
  '--code-bg-color': '#fff',
  '--input-style': 'solid',
  '--display-h1-decoration': 'none',
}